name: tests

on: [push, pull_request]

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf build
          mkdir build && cd build
          cmake ..
          cmake --build .
